name: publication-figure-pack
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.3
  - r-essentials
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-tibble
  - r-ggplot2
  - r-patchwork
  - r-rcolorbrewer
  - r-survival
  - r-survminer
  - bioconductor-complexheatmap
  - bioconductor-circlize